chore: Show weird Lean error
bollu@paracompact-8 ~/n/h/l/Medusa (fp-medusa)> lake build
✖ [28/30] Building Medusa.FP.Generalize
trace: .> ...
error: Medusa/FP/Generalize.lean:1:0: import Medusa.Fp.Basic failed,
environment already contains 'Generalize.Fp.instHashableFpPredicate' from
Medusa.FP.Basic
error: Lean exited with code 1
Some required targets logged failures:
- Medusa.FP.Generalize
error: build failed